### ISSUE TITLE
Compatibility request: Colytra and Elytra Trinket

### ISSUE THREAD

**Issue by BryceBubbles** [CrimsonFluff/ElytraNoFall#2]
Could this be made to work with these mods that equip the elytra differently?

[Colytra](https://www.curseforge.com/minecraft/mc-mods/colytra-fabric) - attribute on chestplate
[Elytra Trinket](https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric) - trinkets cape slot

Rather than just targeting these mods, perhaps there's a way to check if the player is in flight mode without checking if it's equipped?

**Comment by CrimsonFluff** [comment]
I have to check if the Elytra is equipped else it would negate all fall damage from any source, including jumping off a cliff

Ive adding Colytra support in next update and will look into Trinkets support

**Comment by CrimsonFluff** [comment]
Trinkets is done in next update
